### ISSUE TITLE
How to achieve the same terminal working in FlutterApp

### ISSUE THREAD

**Issue by mdzafar3194** [kai-morich/SimpleBluetoothLeTerminal#13]
Hi @kai-morich , i have downloaded the app from Playstore and checked connecting with BluetoothLE Device. It's really working well. Also have checked the (Native App)source code

Now, I have problem where i am trying develop same funtionality in the `Flutter` App. But i am not getting expected output as the Native App.
Trying with this as a reference in Flutter - https://pub.dev/packages/flutter_blue

Please help me out, how can achieve it in flutter. Any help would be appreciated.

**Comment by kai-morich** [comment]
I am not a flutter expert. please ask in flutter community

**Comment by Retr0sec7** [comment]
Hi @mdzafar3194 did you manage to find or get a solution for flutter?

**Comment by mdzafar3194** [comment]
Yes

**Comment by Retr0sec7** [comment]
@mdzafar3194 can you elaborate how did you manage to get it work on flutter please? I used the same flutter package as you, but the machine I'm tryingo to connect is no recognized by taht package, but this Native Android app works fine with it, same situation as yours...

**Comment by mdzafar3194** [comment]
@Retr0sec7 - Sure, I can elaborate
So, I used `flutter_blue` package to communicate the Bluetooth sensor(COZIR) which emits the quality of air. 

You can follow the steps which I have had implemented in my project.

**MUST :** Identify **SERVICE_UUID** and **CHARACTERISTIC_UUID** of your Bluetooth device.

1. Scan for devices - Connect with your Bluetooth device
2. With the connected device, discover the services running in your Bluetooth device
3. Now, loop the discovered services and check with your SERVICE_UUID
4. Once SERVICE_UUID is matched, now check with CHARACTERISTIC_UUID to get the stream
5. Now, you have the stream so that you can listen to stream. 
6. Stream will provide the expected data - (You can decode it using utf8)

Let me know, if you required anything more on this. Will be happy to help you :)
