### ISSUE TITLE
when send data but socket is null

### ISSUE THREAD

**Issue by lilealyh** [kai-morich/SimpleBluetoothLeTerminal#15]
java.lang.NullPointerException: Attempt to invoke virtual method 'void de.kai_morich.simple_bluetooth_le_terminal.SerialSocket.write(byte[])' on a null object reference

service.write(data); call the write function socket.write(data),but socket is NULL.

**Comment by kai-morich** [comment]
error is handled with 2171ba1df3e69d96ccb8650dd413bfa43a08506b
