### ISSUE TITLE
Ble not working in redmi note 9 pro

### ISSUE THREAD

**Issue by Kiran-B-V** [kai-morich/SimpleBluetoothLeTerminal#16]
This was working in redmi note 7 pro. However, with my redmi note 9 pro, i do not get any device when i scan. If i scan from ble settings, i am able to detect my device

**Comment by kai-morich** [comment]
I haven't heard of such issue before. Maybe you have same issue as described [here](https://devzone.nordicsemi.com/f/nordic-q-a/53938/android-10-need-to-toggle-location-permission-to-see-ble-devices)

**Comment by Kiran-B-V** [comment]
I tried this. Toggled the location permission multiple times. But doesn't seem to be working

**Comment by kai-morich** [comment]
Did you modify your fork, e.g. upgraded targetSdkVersion from 28 to 29 in build.gradle as recommended by Android Studio?
If so, location permission handling has to be adapted in the code.

**Comment by Kiran-B-V** [comment]
Actually i am using the "Serial Bluetooth Terminal" android app which i downloaded from app store. This was working for redmi note 7 pro but not working for redmi note 9 pro

**Comment by kai-morich** [comment]
I haven't heard of such issues for other devices. Maybe redmi added their own security enhancements
