### ISSUE TITLE
UUID Serial profile for RN4020

### ISSUE THREAD

**Issue by ElHiero7** [kai-morich/SimpleBluetoothLeTerminal#22]
Hello, First of all, thank you for making this source code available for us. 
This is my first time working with android studio let alone BLE. I used your Serial Bluetooth Terminal from the play store and it works great with my RN4020.  
I noticed in your description you mention that this app " include UUIDs for widely used serial profiles:" such as the Microchip RN4870/1. 
When I scan, I can see my RN4020, but when I hold to select characteristics, nothing happen. When I tap to connect, I get "Connection failed: no serial profile found". I guess it is because the code doesn't include the UUID for the RN20. I opened your SerialSocket.java file and I saw the  "device delegates" section which has all the devices you mentioned. so from my understanding, if I add the delegate for the RN4020, It will work? And if yes, how would I implement that? 

Thank you. 
Sorry for the long text. 

![Screenshot_20210326-224123_Simple_BLE_Terminal 1](https://user-images.githubusercontent.com/61212360/112709133-9a456b00-8e84-11eb-80e9-8fc68f7376b2.jpg)
![Screenshot_20210326-224131_Simple_BLE_Terminal 1](https://user-images.githubusercontent.com/61212360/112709141-a5000000-8e84-11eb-832f-160286cc6631.jpg)

**Comment by kai-morich** [comment]
To add new UUID you should create delegate class and add in `connectCharacteristics1` method

**Comment by ElHiero7** [comment]
Thank you for the feedback. 
It worked.  I am now able to connect. My last question is, I am trying to read some data of an Arduino over UART., When I send "1" byte in the terminal, it is supposed to display a string of information  in the app. But all I get is the 1 I sent. It works fine with your BLE from the app store as you can see in the screenshot. 
Thank You 
![Capture](https://user-images.githubusercontent.com/61212360/113346001-de0ef900-92f8-11eb-8740-2f0e6eaaf664.PNG)

**Comment by kai-morich** [comment]
please check newline character. without or wrong newline many devices do not work

**Comment by ElHiero7** [comment]
Thank you again. It worked.
I was using the wrong UUID
