### ISSUE TITLE
Add "STX/ETX" while Sending and Receiving Commands

### ISSUE THREAD

**Issue by bhavin2887** [kai-morich/SimpleBluetoothLeTerminal#23]
How can I add "STX/ETX" while working with commands. Yes you have provided option of CR+LF, LF and none in NewLine, but can you also specify how to add "STX/ETX"(Start of Text Character/End of Text Character).

**Comment by kai-morich** [comment]
if you need simple solution for send only, you could the characters here https://github.com/kai-morich/SimpleBluetoothLeTerminal/blob/4e8a994043b1c276881b7a9441326bcdd1d136b9/app/src/main/java/de/kai_morich/simple_bluetooth_le_terminal/TerminalFragment.java#L214
