### ISSUE TITLE
Please help on deprecated commands.

### ISSUE THREAD

**Issue by AmiaSharma** [kai-morich/SimpleBluetoothLeTerminal#26]
startLeScan and stopLeScan has been deprecated. It needs to be removed from the code and replaced with startScan and stopScan respectively. please help on this.

file:
DevicesFragment.java
commands:
bluetoothAdapter.startLeScan(null, leScanCallback);
bluetoothAdapter.stopLeScan(leScanCallback);

Thanks a lot :-) 👍

**Comment by kai-morich** [comment]
These methods were deprecated a long time ago, but still exist. Nowadays the old methods are wrappers around the more recent `BluetoothLeScanner` class with old result format. 
I do not expect the deprecated methods to be removed, so I ignore this (and some other) deprecations until it really is removed.
