### ISSUE TITLE
please. can you convert your codes to kotlin

### ISSUE THREAD

**Issue by isakov95** [kai-morich/SimpleBluetoothLeTerminal#27]
Hello dear contributors. can you convert your JAVA file of SimpleBluetoothLeTerminal to KOTLIN. i you do it would be the greatest help for me.

**Comment by piotrek124-1** [comment]
I hope it will help.
https://github.com/piotrek124-1/SimpleBluetoothLeTerminal
Cheers!

**Comment by isakov95** [comment]
oh. dear. thank you very much.

**Comment by isakov95** [comment]
thank you

**Comment by piotrek124-1** [comment]
It was no problem.
If something didn't work feel free to leave a comment (I did it quickly).

**Comment by isakov95** [comment]
understood. thanks a lots.
