### ISSUE TITLE
Notify/Indicate, Increased MTU & Chunking?

### ISSUE THREAD

**Issue by mws-rmain** [kai-morich/SimpleBluetoothLeTerminal#3]
I've been trying to determine if your terminal app &/or any of the supported protocols support: 
- BLE Notify vs BLE Indicate;
- increasing the MTU above 20;
- adding packet sequencing & 'chunking' of large strings (only usefull if BLE Indicate is supported). 

I don't see support for this in this 'Simple' version, and it's not clear if (any of) the supported protocols actually support these features.

Could you please provide some guidance?

**Comment by mws-rmain** [comment]
To clarify - I see your terminal code DOES support Notify / Indicate. If both are supported, indicate (with ACK) is requested preferentially. In this way, the choice of protocol can be determined by the BLE UART server device. This works fine for me, as I have control over this code.

**Comment by kai-morich** [comment]
chunking of larger strings is implemented with write+writeNext methods
Bluetooth LE 4.2 DLE (MTU above 20) is not supported

**Comment by kai-morich** [comment]
larger MTU is supported with https://github.com/kai-morich/SimpleBluetoothLeTerminal/commit/b19d9ba6af4cb298e68c369ed4d5fd1ead39460c
