### ISSUE TITLE
How to restore service after fragment is destoyed

### ISSUE THREAD

**Issue by Semedaki** [kai-morich/SimpleBluetoothLeTerminal#35]
Hi,
Is it possible to retain the service reference, after the fragment is destroyed by the system? 

In some phones when the app is on the background, the activity gets destoyed and also the terminal fragment. When the fragment is recreated, the service reference is null and I have to reconnect again. Is there a way to keep or restore the service?

**Comment by kai-morich** [comment]
the app uses a foreground-service + notification to prevent termination by Android. if it is still terminated on somy devices the app can hardly do anything. could it be stopped due to low memory?

**Comment by Semedaki** [comment]
It was not a low memory issue, turns out the devices with the problem had "don't keep activities" option enabled.
