### ISSUE TITLE
connecting BLE code in flutter app

### ISSUE THREAD

**Issue by n1kh1lmore** [kai-morich/SimpleBluetoothLeTerminal#36]
you are a Ble expert as mentioned below image we are making a final year project in which we are ready with flutter screens but there is a button to connect with ESP for this we are attaching your BLE code to that button and a scanning popup will come and show available devices but not working finally our team decided to contact with you hope you will help us and thank you for your reply

![iPhone 12, 12 Pro – 8](https://user-images.githubusercontent.com/77953441/179528660-ba161e1f-3eaf-4881-a00f-19e16b0e204a.png)

**Comment by n1kh1lmore** [comment]
Thank you for this, but we need little more help

**Comment by Retr0sec7** [comment]
Hi @n1kh1lmore  did you manage to find or get a solution for flutter?

**Comment by n1kh1lmore** [comment]
hey @Retr0sec7,
yes I used flutter_blue package and now working properly, But I need help to make flutter application for thermal Bluetooth printer to print receipt,

**Comment by Retr0sec7** [comment]
@n1kh1lmore is it possible to show us the configuration you made for the flutter_blue instance ?

**Comment by n1kh1lmore** [comment]
What configuration?
