### ISSUE TITLE
Share and Save the recieved Text 

### ISSUE THREAD

**Issue by skhurana36** [kai-morich/SimpleBluetoothLeTerminal#37]
How to share the recieved text or hex code .

**Comment by Maxinun-byte** [comment]
On the terminal page the top right corner(tool bar ) must have options for
saving the text as a text file and sending direct text via Multiple options

**Comment by skhurana36** [comment]
> On the terminal page the top right corner(tool bar ) must have options for saving the text as a text file and sending direct text via Multiple

No There isnt any option of share or save file in the terminal page can you share me the screen shot where to find that option

**Comment by kai-morich** [comment]
I want to keep this app as a simple example, so basically only bugs are fixed, but no features are added
