### ISSUE TITLE
Android studio: Cannot resolve symbol "R"

### ISSUE THREAD

**Issue by lefuturiste** [kai-morich/SimpleBluetoothLeTerminal#4]
I clone this repository and use android studio in it.
I was able to sucessfuly build the project with gradle and upload the app on my app and use the app without a problem.
However I wanted to edit the code and make my own version. And when you use `R` the IDE doesn't seem to understand:

![](https://i.imgur.com/AMupguZ.png)

I try to clean gradle project.
I also try to sync the project with gradle file. 
But It's doesn't work for me.

I'm a begginer with android studio. So If you have any ideas to help me it's will be great.

**Comment by kai-morich** [comment]
I sometimes had similar issues, usually gone after clean build, upgrade gradle, restart studio, ...

**Comment by lefuturiste** [comment]
Thanks for your work, In fact I solved this issue. I forgot to close the issue.
