### ISSUE TITLE
How to add timestamp in the terminal

### ISSUE THREAD

**Issue by Anshullanjewar** [kai-morich/SimpleBluetoothLeTerminal#46]
Hi @kai-morich  I want to add timestamp at starting of line in the terminal. This feature is available in your app from playstore. But when I am trying to implement it the timestamp shows up in between the receiving data. Please help me with it.

**Comment by kai-morich** [comment]
discussed per mail

**Comment by Anshullanjewar** [comment]
> discussed per mail

can you please check my mail
