### ISSUE TITLE
Not getting GNGGA on android 14 devices

### ISSUE THREAD

**Issue by AnkitDev21** [kai-morich/SimpleBluetoothLeTerminal#48]
Hello, I am using this app and it is not working on Android 14 devices, although it works great on devices below 14.

**Comment by kai-morich** [comment]
what is the exact problem on Android 14

**Comment by AnkitDev21** [comment]
Thanks for quick response
I'm trying to get latitude and longitude it's not working on Android 14 I'm using simpleRTK2B
And i have tried all the apps that are on play where it's not working.
Thanks
Ankit

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AnkitDev21** [comment]
Check the screenshots

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kai-morich** [comment]
screenshots are missing

**Comment by AnkitDev21** [comment]
Check now it's attached in mail.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kai-morich** [comment]
looks like mail attachments are not uploaded to github. Better try adding the screenshots in a web browser

**Comment by AnkitDev21** [comment]
![IMG_0822](https://github.com/kai-morich/SimpleBluetoothLeTerminal/assets/98009889/7a16fc56-123d-4f64-8741-b5c20adcb73b)
![IMG_0821](https://github.com/kai-morich/SimpleBluetoothLeTerminal/assets/98009889/2793287b-900b-4bd1-b18c-e625c3c4cda0)
![IMG_0805](https://github.com/kai-morich/SimpleBluetoothLeTerminal/assets/98009889/a3198349-689b-4fc3-8ec4-426357e59609)
![IMG_0804](https://github.com/kai-morich/SimpleBluetoothLeTerminal/assets/98009889/13d1e560-c8e8-47cd-8195-87e0b14b1b70)
Check now

**Comment by AnkitDev21** [comment]
I have tried many apps it's same issue on Android 14 but at least your code is working fine then others 🙂could you check tonfix this for android 14

**Comment by kai-morich** [comment]
The Bluetooth communication is working. Sorry, I cannot help with different content.
