### ISSUE TITLE
how to disconnect bluetooth without using OnbackPressed

### ISSUE THREAD

**Issue by vitor-dev-linux** [kai-morich/SimpleBluetoothLeTerminal#49]
I'm trying to end the pairing with a device connected via Bluetooth, I turned off the public socket to be able to call it, but when I call it I can't disconnect it. How can I ensure disconnection when clicking a button?

**Comment by kai-morich** [comment]
I didn't got your question. Do you want to terminate an existing connection, or cancel connection creation? For the second question I don't know.
