### ISSUE TITLE
Add RNBD451  Transparent UART (similar to BM70/71)

### ISSUE THREAD

**Issue by joeygold** [kai-morich/SimpleBluetoothLeTerminal#50]
Thanks for your hard work.

Can you add the RNBD451  transparent UART
The UUIDs are here
https://onlinedocs.microchip.com/oxy/GUID-26457D23-798C-47B0-9F40-C5DA6E995C6F-en-US-2/GUID-4346AC32-EFE5-4C3D-9D47-59BDC6EF7B7C.html

**Comment by kai-morich** [comment]
RX+TX characteristics are already supported. Please try if it works without control point.

**Comment by joeygold** [comment]
Will try and advise

**Comment by joeygold** [comment]
**Yes, worked thanks!**  I just had to scan for it first.

FYI for future  revisions. 
The  Transparent Control Point  might be useful to remotely control/remotely configure the RNBD451
Transparent Control Point (TCP) | 49535343-4C8A-39B3-2F49-511CFF073B7E | Write, WriteNoResponse, Notify
