### ISSUE TITLE
Support for nRF52840

### ISSUE THREAD

**Issue by ScruffR** [kai-morich/SimpleBluetoothLeTerminal#6]
I just tried to connect to a Particle Argon which exposes UART via these default nRF UUIDs for their UART service/characteristics
```
const BleUuid serviceUuid("6E400001-B5A3-F393-E0A9-E50E24DCCA9E");
const BleUuid rxUuid("6E400002-B5A3-F393-E0A9-E50E24DCCA9E");
const BleUuid txUuid("6E400003-B5A3-F393-E0A9-E50E24DCCA9E");
```

However, I only get `Connection failed: no write characteristic` although it's there and Adafruit Bluefruit recognises it.
At www.kai-morich.de/android/ble_troubleshooting.html it's mentioned that UUIDs could be customised, but I can't find where and how.

**Comment by kai-morich** [comment]
in SimpleBluetoothLeTerminal you should add the UUIDs to app/src/main/java/de/kai_morich/simple_bluetooth_le_terminal/SerialSocket.java. 
In SerialBluetoothTerminal app you can modify the UUIDs with long touch on the device in the Devices tab.
But both should not be necessary as the UUIDs you mention are already included.

Please check that your program on the Adafruit Bluefruit really starts BT connection

**Comment by ScruffR** [comment]
Thanks for the clarification about the custom UUIDs 👍 

> Please check that your program on the Adafruit Bluefruit really starts BT connection
I was actually refering to the _Adafruit Bluefruit Android App_ which *can* communicate with my device while _Serial Bluetooth Terminal_ cannot - that's what threw me off.
