### ISSUE TITLE
not find any ble devices

### ISSUE THREAD

**Issue by thawri1** [kai-morich/SimpleBluetoothLeTerminal#7]
hi.
I test google play version on my two device that support BLE but not find each other.
if two device paired, found in classic section but when connecting show this error:
Read failed, socket might closed or timeout, read ret: -1
I try "SimpleBluetoothTerminal" and "SimpleBluetoothLeTerminal" source code  but show same result.
any help would be appreciated.

**Comment by kai-morich** [comment]
Hi

did you implement the serial profile in your ble devices? 

Kai Morich

Am 28. August 2019 12:46:08 MESZ schrieb hadi ahmadi <notifications@github.com>:

**Comment by thawri1** [comment]
I installed app on two android device and try to communicate with each other. is it important that one device be a microcontroller?

**Comment by kai-morich** [comment]
This app is not for android-to-android communication. The other typically is one of the devices mentioned in README.md
