### ISSUE TITLE
nrf51822 not found

### ISSUE THREAD

**Issue by sashalex007** [kai-morich/SimpleBluetoothLeTerminal#8]
Hi, thanks alot for this code! The full version is able to find and connect to my nrf custom pcb's, but they do not show up in the simple version. The UUID's provided are correct, so far I have not found a solution. 

Thanks for your help

**Comment by kai-morich** [comment]
The SerialSocket class is basically identical. Please look at log output or debug to find out where the device is rejected

**Comment by sashalex007** [comment]
There is nothing that specifically sticks out to me in the logs. Debug is empty, but here is device output from the moment I hit "scan".  The two devices in question are F5:B2:BC:7C:B8:42 and C8:23:DB:BF:14:08. They do appear in the logs, but are never added to listview. 

[output.txt](https://github.com/kai-morich/SimpleBluetoothLeTerminal/files/3575065/output.txt)

**Comment by kai-morich** [comment]
logcat should contain various entries for   SerialSocket. Please check your filter

**Comment by sashalex007** [comment]
Thanks a lot. I can connect just fine by hard coding the address, it just doesn't show up in list view.

**Comment by sashalex007** [comment]
I rewrote DevicesFragment following the new [BLE docs](https://developer.android.com/guide/topics/connectivity/bluetooth-le#java). Works great now, and devices are discovered much faster too.

**Comment by sashalex007** [comment]
Ill get back to you on Monday, out of office until then

**Comment by sashalex007** [comment]
> Hello @sashalex007 could you provide your DeviceFragment updated for custom nRF Boards? I would apprecieate it a lot.

Do you still need this?

**Comment by R-Fehler** [comment]
Yes, please.



sashalex007 <notifications@github.com> schrieb am Mo., 16. Sep. 2019 18:06:

**Comment by kai-morich** [comment]
in my google-play app I implemented both scan methods. to keep this app simple I only implemented `startDiscovery` here, as I did not found much difference. With https://github.com/kai-morich/SimpleBluetoothLeTerminal/commit/f6475a5afd148c86045a1f15c7dce1edaae5da56 I also implemented `leScan`

**Comment by sashalex007** [comment]
@R-Fehler, it should work now. @kai-morich's new code is almost the same as mine.
